import React from "react";
import Head from "next/head";
import Link from "next/link";
import Footer from "./Footer";
import Header from "./Header";

const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title ? title + " - Ecommerce" : "Next Ecommerce"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen relative">
        <Header></Header>
        <main className="sm:container mx-auto">{children}</main>
        <Footer></Footer>
      </div>
    </>
  );
};

export default Layout;
